const menuIcon = [
  { 'id': 1, 'name': '女装上新', 'imgUrl': require('@/assets/images/menuIcon/Women-clothing.png') },
  { 'id': 2, 'name': '男装热卖', 'imgUrl': require('@/assets/images/menuIcon/men-clothing.png') },
  { 'id': 3, 'name': '鞋靴箱包', 'imgUrl': require('@/assets/images/menuIcon/Shoes.png') },
  { 'id': 10, 'name': '内衣配饰', 'imgUrl': require('@/assets/images/menuIcon/underwear.png') },
  { 'id': 12, 'name': '美妆护肤', 'imgUrl': require('@/assets/images/menuIcon/makeups.png') },
  { 'id': 20, 'name': '母婴用品', 'imgUrl': require('@/assets/images/menuIcon/Mother.png') },
  { 'id': 30, 'name': '童装童鞋', 'imgUrl': require('@/assets/images/menuIcon/kids.png') },
  { 'id': 37, 'name': '百货家居', 'imgUrl': require('@/assets/images/menuIcon/Group 4.png') },
  { 'id': 49, 'name': '零食鲜果', 'imgUrl': require('@/assets/images/menuIcon/Fruit.png') },
  { 'id': 57, 'name': '家用电器', 'imgUrl': require('@/assets/images/menuIcon/Electric.png') },
  { 'id': 62, 'name': '手机数码', 'imgUrl': require('@/assets/images/menuIcon/Digital.png') },
  { 'id': 72, 'name': '运动户外', 'imgUrl': require('@/assets/images/menuIcon/Outdoor.png') },
  { 'id': 83, 'name': '图书影音', 'imgUrl': require('@/assets/images/menuIcon/Books.png') },
  { 'id': 89, 'name': '办公文具', 'imgUrl': require('@/assets/images/menuIcon/Office.png') },
  { 'id': 92, 'name': '宠物绿植', 'imgUrl': require('@/assets/images/menuIcon/Pet.png') },
  { 'id': 107, 'name': '玩模乐器', 'imgUrl': require('@/assets/images/menuIcon/Toy.png') },
  { 'id': 98, 'name': '汽车用品', 'imgUrl': require('@/assets/images/menuIcon/Cars.png') },
  { 'id': 111, 'name': '钟表配饰', 'imgUrl': require('@/assets/images/menuIcon/Watch.png') },
  { 'id': 112, 'name': '鲜花礼品', 'imgUrl': require('@/assets/images/menuIcon/Flower.png') },
  { 'id': 135, 'name': '医药保健', 'imgUrl': require('@/assets/images/menuIcon/Health.png') },
  { 'id': 155, 'name': '家装建材', 'imgUrl': require('@/assets/images/menuIcon/Building.png') },
  { 'id': 137, 'name': '游戏动漫', 'imgUrl': require('@/assets/images/menuIcon/Games.png') },
  { 'id': 136, 'name': '文娱教育', 'imgUrl': require('@/assets/images/menuIcon/Education.png') },
  { 'id': 881, 'name': '卡券其他', 'imgUrl': require('@/assets/images/menuIcon/Cards.png') }
]
export default menuIcon
